name: Build

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up vcpkg
        uses: lukka/run-vcpkg@v11

      - name: Configure and Build
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'default'
          buildPreset: 'default'

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: prune-windows
          path: |
            build/Release/Prune.exe
            build/Prune.exe
          retention-days: 30